spring.application.name=resume-analyzer

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

server.port=${PORT:8081}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
